apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/sleepr-404515/notifications/production
        name: notifications
        env:
          - name: PORT
            value: "3000"
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 227071940267-bgqr8u67a92dlnk556cobul7vvoobdbm.apps.googleusercontent.com
          - name: SMTP_USER
            value: moswilamdev@gmail.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3000
