steps:
  # AUTH APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-404515/auth/production']


  # RESERVATIONS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-404515/reservations/production']


  # PAYMENTS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-404515/payments/production']


  # notifications APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-404515/notifications/production']