steps:
  # AUTH APP
  # BUILD DOCKER IMAGE

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo echo $(git describe --tags --abbrev=7)
        echo $(date +%Y%m%d)
        echo "Full tag: $(git describe --tags --abbrev=7)-$(date +%Y%m%d)"

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/auth/production:1.0.1',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]

  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/auth/production:1.0.1']



  # RESERVATIONS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production:1.0.1',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production:1.0.1']


  # PAYMENTS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/payments/production:1.0.1',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/payments/production:1.0.1']


  # notifications APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production:1.0.1',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production:1.0.1']