steps:
  # AUTH APP
  # BUILD DOCKER IMAGE

  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo echo $(git describe --tags --abbrev=7)
  #       echo $(date +%Y%m%d)
  #       echo "Full tag: $(git describe --tags --abbrev=7)-$(date +%Y%m%d)"

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr2/auth/prod:latest',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]

  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr2/auth/prod:latest']



  # RESERVATIONS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr2/reservations/prod:latest',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr2/reservations/prod:latest']


  # PAYMENTS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr2/payments/prod:latest',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr2/payments/prod:latest']


  # notifications APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr2/notifications/prod:latest',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr2/notifications/prod:latest']