steps:
  # AUTH APP BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]

  # NOTIFICATIONS APP BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]

  # PAYMENTS APP BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]

  # notifications APP BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-404515/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]