steps:
  # AUTH APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/auth/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]

  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/auth/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)']



  # RESERVATIONS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)']


  # PAYMENTS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/payments/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/payments/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)']


  # notifications APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production:$(git describe --tags --abbrev=7)-$(date +%Y%m%d)']