steps:
  # AUTH APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]

  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/auth/production']



  # RESERVATIONS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/reservations/production']


  # PAYMENTS APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/payments/production']


  # notifications APP
  # BUILD DOCKER IMAGE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  # PUSH DOCKER IMAGE TO GCP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/sleepr-417301/notifications/production']