// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v5.26.1
// source: proto/payments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export interface ChargeRequest {
  email: string;
  amount: number;
  card: CardMessage | undefined;
}

export interface CardMessage {
  number: string;
  cvc: string;
  expMonth: number;
  expYear: number;
}

export interface ChargeResponse {
  id: string;
}

export const PAYMENTS_PACKAGE_NAME = 'payments';

export interface PaymentServiceClient {
  createCharge(request: ChargeRequest): Observable<ChargeResponse>;
}

export interface PaymentServiceController {
  createCharge(
    request: ChargeRequest,
  ): Promise<ChargeResponse> | Observable<ChargeResponse> | ChargeResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createCharge'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('PaymentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('PaymentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PAYMENT_SERVICE_NAME = 'PaymentService';
