apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/sleepr2/reservations/prod:latest
        name: reservations
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/auth"
        - name: PORT
          value: "3004"
        - name: AUTH_HOST
          value: "auth-tcp"
        - name: AUTH_PORT
          value: "3002"
        - name: PAYMENTS_HOST
          value: "payments"
        - name: PAYMENTS_PORT
          value: "3001"
        ports:
        - containerPort: 3004

